# yaml-language-server: $schema=https://coderabbit.ai/export/schema.json
language: "en-US"
reviews:
  profile: "chill"
  request_changes_workflow: false
  auto_review:
    enabled: true
    base_branches:
      - "main"
      - "feature/coderabbit-review"
