packages:
  - "."
  - "packages/*"

ignoredBuiltDependencies:
  - esbuild

overrides:
  fetch-blob: "^4.0.0"

peerDependencyRules:
  ignoreMissing:
    - "storybook"
  allowedVersions:
    tailwindcss-animate:
      tailwindcss: "*"
