packages:
  - "."
  - "packages/*"

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - "@bundled-es-modules/glob"
  - "core-js"
  - "esbuild"
  - "msw"
  - "style-dictionary"

overrides:
  fetch-blob: "^4.0.0"

peerDependencyRules:
  ignoreMissing:
    - "storybook"
  allowedVersions:
    tailwindcss-animate:
      tailwindcss: "*"
